### ISSUE TITLE
请问与 PHP-CPP 比有什么优劣，还是都是一种解决方案。

### ISSUE THREAD

**Issue by Liv1020** [swoole/PHP-X#1]
之前一直用 [PHP-CPP](http://www.php-cpp.com/)
，但是看到Rango除了PHP-X当然要用了，但是发现好相似，能否就PHP-CPP对比一下？

**Comment by matyhtf** [comment]
1. `PHP-CPP`性能较差，`PHP-X`进行了大量性能优化，C++扩展函数性能甚至比标准的PHP扩展性能更高
2. `PHP-CPP`实现复杂，`PHP-X`更简单
3. `PHP-CPP`的API不友好，学习成本高，`PHP-X`的API更友好，学习成本低，几乎可以立即上手
4. `PHP-CPP`提供的功能没有`PHP-X`，比如`PHP-CPP`不支持`Resource`，不支持`Embed`，还有很多底层的`Zend API`没有提供封装，而`PHP-X`全部提供了
