### ISSUE TITLE
mac os下 Build extension make的时候报错 

### ISSUE THREAD

**Issue by jackwangshukai** [swoole/PHP-X#25]
编译 cpp_ext 扩展的时候 报了这个clang: error: linker command failed with exit code 1 (use -v to see invocation)  错误
大概是什么原因呢。

**Comment by mw258176257** [comment]
mac 下编译出这个错误：
c++ -DHAVE_CONFIG_H -g -o cpp_ext.so -O0 -fPIC -shared extension.cpp -std=c++11 -lphpx `php-config --includes` -I`php-config --include-dir`
Undefined symbols for architecture x86_64:
  "___zend_malloc", referenced from:
      php::Variant::Variant(char const*) in extension-1eab60.o
      php::String::String(char const*) in extension-1eab60.o
  "__array_init", referenced from:
      php::Array::Array(php::Variant const&) in extension-1eab60.o
  "__efree", referenced from:
      php::String::~String() in extension-1eab60.o
  "__emalloc", referenced from:
      php::Variant::Variant(char const*) in extension-1eab60.o
      php::String::String(char const*) in extension-1eab60.o
  "__zval_ptr_dtor", referenced from:
      php::Variant::~Variant() in extension-1eab60.o
  "_add_index_zval", referenced from:
      php::Array::set(int, php::Variant const&) in extension-1eab60.o
  "_zend_fetch_resource", referenced from:
      php::String* php::Variant::toResource<php::String>(char const*) in extension-1eab60.o
  "_zend_read_property", referenced from:
      php::Object::get(char const*) in extension-1eab60.o
  "_zend_register_resource", referenced from:
      php::Variant php::newResource<php::String>(char const*, php::String*) in extension-1eab60.o
  "_zend_update_property", referenced from:
      php::Object::set(char const*, php::Variant const&) in extension-1eab60.o
  "_zval_add_ref", referenced from:
      php::Variant::addRef() in extension-1eab60.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [cpp_ext.so] Error 1

**Comment by qcoreteam** [comment]
LINK_FLAGS " -undefined dynamic_lookup " 试试 加上链接参数
