### ISSUE TITLE
添加扩展配置到.ini文件时产生了警告

### ISSUE THREAD

**Issue by HanSon** [swoole/PHP-X#34]
根据 https://segmentfault.com/a/1190000011111074?from=timeline&isappinstalled=0 操作

当把 `extension=test.so` 加到 php.ini 文件时，提示 

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/test.so' - /usr/local/lib/libphpx.so: undefined symbol: json_globals in Unknown on line 0
```

当加 `extension=json.so` 在 test.so 上一行却提示 

```
PHP Warning:  Module 'json' already loaded in Unknown on line 0
```

**Comment by owenliang** [comment]
需要将JSON扩展随PHP一起编译，不要作为独立扩展存在。

**Comment by HanSon** [comment]
通过 apt-get 安装的就玩不起来么？一定要编译安装？

**Comment by owenliang** [comment]
目前是这样的，直接调用其他扩展的C符号，比通过Zend内核调用要快。

**Comment by matyhtf** [comment]
json扩展加载放到 `extension=test.so` 之前就可以了。上面的错误是因为同时存在2个 `extension=json.so` ，你可以删除另外一个。
