### ISSUE TITLE
扩展调用

### ISSUE THREAD

**Issue by bucaixiaot** [swoole/PHP-X#4]
我没有找到怎么调用另外的扩展，比如我想在我的扩展中调用swoole扩展，或者php自带的数组扩展。

**Comment by matyhtf** [comment]
https://wiki.swoole.com/wiki/page/742.html

**Comment by matyhtf** [comment]
直接使用`php::exec`执行其他扩展的函数，或者 `php::newObject` 创建其他扩展提供的类的对象。

**Comment by bucaixiaot** [comment]
感谢你大哥指点
