### ISSUE TITLE
ubuntu 上编译报错

### ISSUE THREAD

**Issue by hanlicun** [swoole/PHP-X#7]
c++ -DHAVE_CONFIG_H -g -o cpp_ext.so -O0 -fPIC -shared extension.cpp -std=c++11 -lphpx `php-config --includes` -I`php-config --include-dir`
/usr/bin/ld: 找不到 -lphpx
collect2: error: ld returned 1 exit status
Makefile:8: recipe for target 'cpp_ext.so' failed
make: *** [cpp_ext.so] Error 1

**Comment by matyhtf** [comment]
这个错误表示找不到`libphpx.so`，你需要先编译安装 php-x

**Comment by 52fhy** [comment]
```
1、编译PHP 
2、将PHP-X clone后放到PHP源码根目录 
3、先编译安装 php-x
4、再编译cpp_ext扩展
5、sudo cp /usr/local/lib/libphpx.so /usr/lib/
```
