### ISSUE TITLE
 libphpx.so: cannot open shared object file

### ISSUE THREAD

**Issue by benlee7** [swoole/PHP-X#8]
按照文档的说明，一直到最后php echo.php时，提示这样的错误：
Warning: PHP Startup: Unable to load dynamic library '/usr/local/php/lib/php/extensions/no-debug-non-zts-20151012/cpp_ext.so' - libphpx.so: cannot open shared object file: No such file or directory in Unknown on line 0
而这个扩展文件 /usr/local/php/lib/php/extensions/no-debug-non-zts-20151012/cpp_ext.so 是存在的，这是什么问题呢？

php 版本7.0.19
gcc 版本4.8.0

**Comment by ipengxh** [comment]
应该是动态库目录不对，见： https://github.com/swoole/PHP-X/issues/5
